<?php

declare(strict_types=1);

/**
 * NOTÍCIAS E ARTIGOS
 *
 * Para publicar, adicione um item NO COMEÇO da lista (a mais nova primeiro).
 * Cada item vira a página /noticias/{id} (use só letras minúsculas, números e hífen no id).
 *
 *   body          cada texto vira um parágrafo; ['heading' => '...'] vira subtítulo;
 *                 ['ad' => true] marca onde entra o anúncio do meio do texto
 *   related_tools ids das calculadoras mostradas no fim da notícia (veja content/tools.php)
 *   image         SEMPRE uma foto de verdade (nada de ícone ou desenho), em public/assets/img/news/
 *                 com o mesmo nome do id. Use fotos livres (domínio público/CC0) e salve em JPG
 *                 com 960 px de largura. image_alt descreve a foto; image_credit dá o crédito.
 */

return [
    [
        'id' => 'decimo-terceiro-2026-datas',
        'title' => '13º salário 2026: datas da 1ª e da 2ª parcela e quanto você recebe',
        'category' => 'Trabalho',
        'date' => '2026-10-01',
        'image' => 'decimo-terceiro-2026-datas.jpg',
        'image_alt' => 'Pessoa fazendo contas numa calculadora sobre papéis e gráficos',
        'image_credit' => 'Foto: Tevarak / StockSnap (CC0)',
        'summary' => 'A 1ª parcela vence em 30 de novembro e a 2ª, em 18 de dezembro, porque o dia 20 cai num domingo. Veja exemplos de valores líquidos.',
        'related_tools' => ['decimo-terceiro', 'salario-liquido', 'quanto-posso-gastar'],
        'body' => [
            'Em 2026, quem trabalha com carteira assinada deve receber a primeira parcela do 13º salário até segunda-feira, 30 de novembro. A segunda parcela tem prazo legal até 20 de dezembro, mas a data cai num domingo: por isso, a orientação é que as empresas paguem até sexta-feira, 18 de dezembro.',
            'A empresa pode pagar antes, e também pode pagar tudo de uma vez, desde que seja até 30 de novembro. Convenções coletivas podem prever datas próprias.',
            ['heading' => 'Por que a 2ª parcela vem menor'],
            'A primeira parcela é metade do 13º, sem nenhum desconto. Na segunda são descontados o INSS e o Imposto de Renda, calculados sobre o 13º inteiro. Por isso a segunda parcela é sempre menor que a primeira.',
            'O Imposto de Renda do 13º é calculado separado do salário do mês, e a redução criada pela Lei 15.270/2025 também vale para ele: quem tem 13º menor que R$ 5.000 não paga imposto.',
            ['ad' => true],
            ['heading' => 'Exemplos com 12 meses trabalhados e sem dependentes'],
            'Salário de R$ 1.621 (salário mínimo de 2026): 1ª parcela de R$ 810,50 e 2ª de R$ 688,93, com R$ 121,57 de INSS. Total líquido: R$ 1.499,43.',
            'Salário de R$ 2.000: 1ª parcela de R$ 1.000,00 e 2ª de R$ 844,31. Total líquido: R$ 1.844,31.',
            'Salário de R$ 2.500: 1ª parcela de R$ 1.250,00 e 2ª de R$ 1.049,31. Total líquido: R$ 2.299,31.',
            'Salário de R$ 3.000: 1ª parcela de R$ 1.500,00 e 2ª de R$ 1.251,40. Total líquido: R$ 2.751,40.',
            'Salário de R$ 4.000: 1ª parcela de R$ 2.000,00 e 2ª de R$ 1.631,40. Total líquido: R$ 3.631,40.',
            'Para o seu salário, com dependentes ou com menos meses trabalhados, use a calculadora de 13º do iCalculei.',
            ['heading' => 'Quem trabalhou menos de um ano'],
            'O 13º é proporcional: o salário dividido por 12 e multiplicado pelos meses trabalhados no ano. Conta como mês inteiro aquele em que a pessoa trabalhou pelo menos 15 dias. Quem foi contratado em abril, por exemplo, recebe 9/12 do salário.',
            'Horas extras, adicional noturno e comissões habituais também entram no 13º, pela média do ano. Por isso o valor pode ser maior que o do exemplo.',
            ['heading' => 'E se a empresa não pagar no prazo'],
            'O atraso no pagamento do 13º pode gerar multa para a empresa na fiscalização do trabalho. O trabalhador pode procurar o sindicato da categoria ou registrar denúncia nos canais do Ministério do Trabalho e Emprego.',
            ['heading' => 'Antes de gastar'],
            'O 13º chega junto com a Black Friday e as compras de fim de ano. Vale separar primeiro as contas de janeiro, como IPVA, IPTU e material escolar, e quitar dívidas caras, como cartão de crédito e cheque especial.',
        ],
    ],
    [
        'id' => 'black-friday-2026-orcamento',
        'title' => 'Black Friday 2026: como definir quanto gastar sem se endividar',
        'category' => 'Dinheiro',
        'date' => '2026-10-01',
        'image' => 'black-friday-2026-orcamento.jpg',
        'image_alt' => 'Mão encostando um cartão numa maquininha de pagamento',
        'image_credit' => 'Foto: rawpixel (CC0)',
        'summary' => 'A Black Friday cai em 27 de novembro. Veja como montar um teto de gastos, conferir se o desconto é real e quando o parcelamento pesa.',
        'related_tools' => ['quanto-posso-gastar', 'porcentagem', 'dias-ate-data', 'juros-compostos'],
        'body' => [
            'A Black Friday de 2026 será na sexta-feira, 27 de novembro. No Brasil, a data segue a dos Estados Unidos: é sempre a sexta-feira depois da quarta quinta-feira de novembro. Muitas lojas começam as ofertas dias antes.',
            'A data fica entre o pagamento da 1ª parcela do 13º, até 30 de novembro, e as contas de começo de ano. Por isso, sem um limite definido antes, é fácil comprometer o orçamento de janeiro.',
            ['heading' => '1. Defina um teto antes de olhar as ofertas'],
            'Some a renda líquida do mês e tire os gastos fixos, as parcelas que já existem e o que você quer guardar. O que sobra é o limite para compras e lazer. A calculadora Quanto posso gastar por mês faz essa conta e mostra também o valor por semana e por dia.',
            'Se houver dívidas de cartão ou cheque especial, quitá-las costuma render mais que qualquer desconto: os juros dessas dívidas estão entre os mais altos do país.',
            ['ad' => true],
            ['heading' => '2. Faça uma lista e acompanhe os preços desde já'],
            'Anote o que realmente precisa comprar e o preço de hoje de cada item. Assim, no dia, você sabe se o desconto é real ou se o preço subiu antes para cair depois. Na calculadora de porcentagem, a opção Variação mostra o desconto verdadeiro entre o preço anotado e o preço da oferta.',
            ['heading' => '3. Cuidado com o parcelamento'],
            'Parcelas sem juros também comprometem a renda dos próximos meses. Uma referência comum é não passar de 30% da renda líquida com parcelas. Antes de parcelar, some as parcelas novas às que você já tem.',
            'Se a compra tiver juros, compare o preço total parcelado com o preço à vista. Muitas vezes o desconto à vista é maior que o rendimento de deixar o dinheiro aplicado.',
            ['heading' => '4. Proteja-se de golpes'],
            'Desconfie de preços muito abaixo do mercado, confira o endereço do site antes de pagar e prefira lojas conhecidas. Em compras pela internet, o Código de Defesa do Consumidor garante 7 dias para desistir da compra, a contar do recebimento.',
        ],
    ],
    [
        'id' => 'feriados-novembro-2026',
        'title' => 'Feriados de novembro de 2026: dois feriadões e um feriado no domingo',
        'category' => 'Dia a dia',
        'date' => '2026-10-01',
        'image' => 'feriados-novembro-2026.jpg',
        'image_alt' => 'Óculos sobre uma agenda aberta nos dias de sexta, sábado e domingo',
        'image_credit' => 'Foto: Jess Watters / StockSnap (CC0)',
        'summary' => 'Finados cai na segunda e a Consciência Negra na sexta: são dois fins de semana de três dias. A Proclamação da República cai num domingo.',
        'related_tools' => ['dias-uteis', 'custo-de-viagem', 'dias-ate-data', 'hora-extra'],
        'body' => [
            'Novembro de 2026 tem três feriados nacionais. Dois deles emendam com o fim de semana e formam feriadões de três dias; o terceiro cai num domingo.',
            ['heading' => 'As datas'],
            'Finados, segunda-feira, 2 de novembro: feriadão de sábado, 31 de outubro, a segunda-feira, 2 de novembro.',
            'Proclamação da República, domingo, 15 de novembro: não gera folga extra para quem já descansa aos domingos.',
            'Dia Nacional de Zumbi e da Consciência Negra, sexta-feira, 20 de novembro: feriadão de sexta a domingo, 22 de novembro. A data é feriado nacional desde a Lei 14.759/2023.',
            'Alguns estados e cidades têm feriados próprios no mês, como o Dia do Evangélico em 30 de novembro no Distrito Federal e em Alagoas. Confira a lista do seu estado no calendário de feriados do iCalculei.',
            ['ad' => true],
            ['heading' => 'Dias úteis no mês'],
            'Com os feriados de 2 e 20 de novembro em dias de semana, novembro de 2026 tem 19 dias úteis de segunda a sexta. Isso afeta prazos em dias úteis, como boletos, entregas e prazos de documentos.',
            ['heading' => 'Quem trabalha no feriado'],
            'Quem trabalha num feriado sem folga compensatória em outro dia tem direito a receber em dobro, segundo a Lei 605/1949. Na prática, muitas convenções coletivas tratam essas horas como extras de 100%. A calculadora de hora extra mostra o valor com o DSR e os descontos.',
            ['heading' => 'Vai viajar?'],
            'Os feriadões costumam ter estradas cheias e passagens mais caras. Para viagens de carro, simule o combustível e os pedágios do trajeto antes de sair na calculadora de custo de viagem.',
        ],
    ],
    [
        'id' => 'ferias-coletivas-fim-de-ano',
        'title' => 'Férias coletivas de fim de ano: regras e quanto você recebe',
        'category' => 'Trabalho',
        'date' => '2026-10-01',
        'image' => 'ferias-coletivas-fim-de-ano.jpg',
        'image_alt' => 'Família na beira de um lago com um guarda-sol, montanhas ao fundo',
        'image_credit' => 'Foto: Salvatore Ventura / StockSnap (CC0)',
        'summary' => 'Muitas empresas param entre o Natal e o Ano-novo. Veja o que diz a CLT, quem tem menos de um ano de casa e como calcular o valor.',
        'related_tools' => ['ferias', 'salario-liquido', 'decimo-terceiro'],
        'body' => [
            'As férias coletivas são dadas ao mesmo tempo para todos os empregados da empresa, ou de um setor. São comuns no fim do ano, quando o movimento cai entre o Natal e o Ano-novo.',
            ['heading' => 'O que diz a CLT'],
            'As regras estão nos artigos 139 a 141 da CLT. As férias coletivas podem ser divididas em até dois períodos por ano, e nenhum deles pode ter menos de 10 dias corridos.',
            'A empresa precisa avisar com pelo menos 15 dias de antecedência o Ministério do Trabalho e Emprego e o sindicato da categoria, e afixar o aviso no local de trabalho. Microempresas e empresas de pequeno porte não precisam avisar o Ministério.',
            ['ad' => true],
            ['heading' => 'Quem tem menos de um ano de empresa'],
            'Quem ainda não completou 12 meses de trabalho tira férias proporcionais aos meses trabalhados. Ao voltar, começa a contar um novo período aquisitivo. Se os dias de férias coletivas forem mais que os proporcionais, os dias a mais costumam ser tratados como licença remunerada.',
            ['heading' => 'Quanto você recebe'],
            'O cálculo é o mesmo das férias individuais: o salário proporcional aos dias de férias, mais um terço. Sobre esse valor são descontados INSS e Imposto de Renda. Para 10 dias, por exemplo, o valor bruto é um terço do salário mais o adicional de 1/3.',
            'O pagamento deve sair até 2 dias antes do início das férias. Por isso, quem sai de férias no fim de dezembro costuma receber as férias perto da 2ª parcela do 13º, e o salário de janeiro vem menor, só com os dias trabalhados.',
            ['heading' => 'Venda de dias (abono)'],
            'Nas férias coletivas, a conversão de um terço das férias em dinheiro depende de acordo coletivo entre a empresa e o sindicato; não é um pedido individual.',
            'Use a calculadora de férias do iCalculei para ver o valor líquido de acordo com o número de dias.',
        ],
    ],
    [
        'id' => 'decimo-terceiro-quem-tem-direito',
        'title' => '13º salário: quem tem direito e como são pagas as parcelas',
        'category' => 'Trabalho',
        'date' => '2026-09-29',
        'image' => 'decimo-terceiro-quem-tem-direito.jpg',
        'image_alt' => 'Notas de real espalhadas sobre a mesa',
        'image_credit' => 'Foto: rawpixel (domínio público)',
        'summary' => 'Entenda o cálculo proporcional, os prazos das duas parcelas e por que a segunda vem menor.',
        'related_tools' => ['decimo-terceiro', 'ferias', 'salario-liquido'],
        'body' => [
            'O 13º salário é um direito de quem trabalha com carteira assinada, e também de aposentados e pensionistas do INSS. Ele é pago em duas parcelas e equivale a um salário a mais por ano para quem trabalhou os 12 meses.',
            ['heading' => 'Como é o cálculo proporcional'],
            'Quem trabalhou menos de um ano recebe o valor proporcional: o salário dividido por 12 e multiplicado pelos meses trabalhados. Cada mês em que a pessoa trabalhou pelo menos 15 dias conta como mês inteiro.',
            ['ad' => true],
            ['heading' => 'Por que a segunda parcela vem menor'],
            'A primeira parcela corresponde à metade do valor, sem descontos. Os descontos de INSS e Imposto de Renda são feitos na segunda parcela, calculados sobre o valor total do 13º. Por isso ela costuma ser menor.',
            'Desde 2026, a redução do Imposto de Renda criada pela Lei 15.270/2025 também vale para o 13º: quem tem 13º de até R$ 5.000 não paga imposto sobre ele. Use a calculadora de 13º do iCalculei para ver o valor de cada parcela.',
        ],
    ],
    [
        'id' => 'selic-e-investimentos',
        'title' => 'Como a taxa Selic influencia seus investimentos',
        'category' => 'Dinheiro',
        'date' => '2026-09-26',
        'image' => 'selic-e-investimentos.jpg',
        'image_alt' => 'Notebook mostrando gráfico da bolsa de valores',
        'image_credit' => 'Foto: Negative Space / StockSnap (domínio público)',
        'summary' => 'Quando a Selic sobe ou desce, muda o rendimento da renda fixa e o custo das dívidas. Veja como.',
        'related_tools' => ['juros-compostos', 'juros-simples', 'financiamento'],
        'body' => [
            'A Selic é a taxa básica de juros da economia brasileira, definida pelo Comitê de Política Monetária do Banco Central. Ela serve de referência para quase todos os outros juros do país.',
            ['heading' => 'O que acontece com a renda fixa'],
            'Investimentos pós-fixados, como o Tesouro Selic e muitos CDBs, acompanham a taxa. Quando ela sobe, esses investimentos passam a render mais; quando cai, rendem menos.',
            ['ad' => true],
            ['heading' => 'E com as dívidas'],
            'Juros de empréstimos e financiamentos também tendem a acompanhar a Selic. Antes de contratar um financiamento, simule as parcelas e compare os sistemas de amortização Price e SAC.',
        ],
    ],
    [
        'id' => 'alcool-ou-gasolina',
        'title' => 'Álcool ou gasolina: a regra dos 70% ainda vale?',
        'category' => 'Dia a dia',
        'date' => '2026-09-22',
        'image' => 'alcool-ou-gasolina.jpg',
        'image_alt' => 'Bicos de bomba de combustível em um posto',
        'image_credit' => 'Foto: rawpixel (domínio público)',
        'summary' => 'A conta clássica para decidir no posto, e quando vale a pena fazer o teste no seu próprio carro.',
        'related_tools' => ['alcool-gasolina', 'consumo'],
        'body' => [
            'A regra mais conhecida diz que o etanol compensa quando custa até 70% do preço da gasolina. Isso acontece porque, em média, um carro flex roda cerca de 30% menos com etanol.',
            ['heading' => 'Por que o seu carro pode ser diferente'],
            'A diferença de consumo varia de modelo para modelo. Alguns carros perdem menos de 30% com etanol, e aí o limite fica acima de 70%.',
            ['ad' => true],
            'A forma mais precisa é medir: encha o tanque, anote a quilometragem e calcule o consumo com cada combustível usando a calculadora de consumo.',
        ],
    ],
    [
        'id' => 'imc-o-que-diz',
        'title' => 'IMC: o que o número diz (e o que ele não diz)',
        'category' => 'Saúde',
        'date' => '2026-09-18',
        'image' => 'imc-o-que-diz.jpg',
        'image_alt' => 'Balança de banheiro com uma fita métrica',
        'image_credit' => 'Foto: rawpixel (domínio público)',
        'summary' => 'O índice é útil como triagem, mas não mede gordura corporal. Entenda os limites.',
        'related_tools' => ['imc', 'calorias', 'agua'],
        'body' => [
            'O Índice de Massa Corporal relaciona peso e altura e é usado no mundo todo como uma forma rápida de triagem.',
            ['heading' => 'As limitações'],
            'O IMC não diferencia músculo de gordura. Uma pessoa muito musculosa pode ter IMC de sobrepeso sem ter excesso de gordura.',
            ['ad' => true],
            'Por isso ele deve ser visto junto com outras medidas, como a circunferência da cintura, e sempre com orientação de um profissional de saúde.',
        ],
    ],
    [
        'id' => 'hora-extra-como-calcular',
        'title' => 'Hora extra: como calcular o valor com adicional de 50% ou 100%',
        'category' => 'Trabalho',
        'date' => '2026-09-15',
        'image' => 'hora-extra-como-calcular.jpg',
        'image_alt' => 'Despertador sobre uma mesa',
        'image_credit' => 'Foto: Negative Space / StockSnap (domínio público)',
        'summary' => 'Descubra o valor da sua hora de trabalho e quanto recebe por cada hora a mais.',
        'related_tools' => ['hora-extra', 'somar-horas', 'salario-liquido'],
        'body' => [
            'Pela CLT, a hora extra vale pelo menos 50% a mais que a hora normal. Em domingos e feriados, muitas convenções coletivas preveem 100%.',
            ['heading' => 'Passo a passo'],
            'Primeiro divida o salário pela jornada mensal (220 horas para quem trabalha 44 horas por semana). Depois aplique o adicional e multiplique pela quantidade de horas extras.',
            ['ad' => true],
            'Confira sempre a convenção coletiva da sua categoria: ela pode prever adicionais maiores do que o mínimo da lei.',
        ],
    ],
];
